name: Deploy Glue Jobs

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-1
  S3_BUCKET: regularpython-batch-realestate

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Zip the src folder (Custom Modules)
      - name: Zip src folder
        run: |
          cd src
          zip -r ../src.zip .
          cd ..

      # Upload Glue Script
      - name: Upload Glue Script to S3
        run: |
          aws s3 cp jobs/bronze_layer.py s3://${S3_BUCKET}/bronze_layer.py

      # Upload Custom Modules ZIP
      - name: Upload src.zip to S3
        run: |
          aws s3 cp src.zip s3://${S3_BUCKET}/src.zip

      # Optional: Verify Upload
      - name: List S3 Files
        run: |
          aws s3 ls s3://${S3_BUCKET}/